COMPUTED VALUES:
annotations: {}
config: null
count: 1
elasticsearchRef:
  name: eck-elasticsearch
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    path: /
  labels: {}
  pathType: Prefix
  tls:
    enabled: false
labels: {}
monitoring: {}
secureSettings: []
version: 9.2.0
