COMPUTED VALUES:
annotations: {}
config: null
count: 1
elasticsearchRef:
  name: eck-elasticsearch
  value: eck-operator
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    path: /
  labels: {}
  pathType: Prefix
  tls:
    enabled: false
labels: {}
monitoring: {}
secureSettings: []
version: 9.2.0
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 60
  successThreshold: 3
  timeoutSeconds: 5
