agent:
  name: wazuh-agent
  image:
    registry: "ghcr.io"
    repository: avistotelecom/docker-wazuh-agent
    tag: "4.12.0"
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  configuration:
    joinManagerMasterHost: "host.docker.internal"
    joinManagerProtocol: "https"
    joinManagerApiPort: "55000"
    joinManagerPort: "1514"
    username: "admin"
    password: "NoPassw"
    wazuhGroups: "default"
    configProfile: "debian, debian12"
    rootcheck: ""
    ciscat: ""
    osquery: ""
    syscollector: ""
    sca: ""
    syscheck: ""
    loganalysis: ""
    activeresponse: ""
    logformat: ""
    additionalconfig: ""
  existingConfigmap: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  command: []
  args: []
  livenessProbe:
    enabled: true
    initialDelaySeconds: 40
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 40
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  resources:
    limits: {}
    requests: {}
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsGroup: 0
    privileged: true
    readOnlyRootFilesystem: false  
    allowPrivilegeEscalation: true
  containerPorts:
    http: 5000
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  extraVolumeMounts: []
  extraVolumes: []
  automountServiceAccountToken: false  # <-- move it here, under agent, not extraPodSpec