

_internal_defaults_do_not_set:
  global:

    
    
    
    imagePullSecrets: []

    
    istioNamespace: istio-system

    
    
    
    
    
    
    resourceScope: all
  base:
    
    
    
    excludedCRDs: []
    
    
    
    
    
    
    enableCRDTemplates: true

    
    
    validationURL: ""
    
    validationCABundle: ""

    
    enableIstioConfigCRDs: true

  defaultRevision: "default"
  experimental:
    stableValidationPolicy: false
