apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/sidhuni/apps-repo.git"
    targetRevision: main
    path: apps/chartmuseum
    helm:
      repoURL: "https://chartmuseum.github.io/charts"
      chart: chartmuseum
      targetRevision: "3.10.1"
      valueFiles:
        - values.yaml   # loads apps/chartmuseum/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: chartmuseum
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
