global:
  image:
    registry: null
  dnsConfig: {}
image:
  keda:
    registry: ghcr.io
    repository: kedacore/keda
    tag: ""
  metricsApiServer:
    registry: ghcr.io
    repository: kedacore/keda-metrics-apiserver
    tag: ""
  webhooks:
    registry: ghcr.io
    repository: kedacore/keda-admission-webhooks
    tag: ""
  pullPolicy: Always
clusterName: kubernetes-default
clusterDomain: cluster.local
crds:
  install: true
  additionalAnnotations:
    {}
watchNamespace: ""
imagePullSecrets: []
networkPolicy:
  enabled: false
  flavor: "cilium"
  cilium:
    operator:
      extraEgressRules: []
  kubernetes:
    operator:
      extraEgressRules: []
    metricsServer:
      extraEgressRules: []
    webhooks:
      extraEgressRules: []
operator:
  name: keda-operator
  revisionHistoryLimit: 10
  replicaCount: 1
  disableCompression: true
  dnsConfig: {}
  dnsPolicy: ClusterFirst
  useHostNetwork: false
  affinity: {}
  extraContainers: []
  extraInitContainers: []
resources:
  operator:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metricServer:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  webhooks:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
nodeSelector: {}
tolerations: []
hostAliases: []
topologySpreadConstraints:
  operator: []
  metricsServer: []
  webhooks: []
affinity: {}
priorityClassName: ""
http:
  timeout: 3000
  keepAlive:
    enabled: true
  minTlsVersion: TLS12
profiling:
  operator:
    enabled: false
    port: 8082
  metricsServer:
    enabled: false
    port: 8083
  webhooks:
    enabled: false
    port: 8084
extraArgs:
  keda: {}
  metricsAdapter: {}
env: []
volumes:
  keda:
    extraVolumes: []
    extraVolumeMounts: []
  metricsApiServer:
    extraVolumes: []
    extraVolumeMounts: []
  webhooks:
    extraVolumes: []
    extraVolumeMounts: []
prometheus:
  metricServer:
    enabled: false
    port: 8080
    portName: metrics
    serviceMonitor:
      enabled: false
      jobLabel: ""
      targetLabels: []
      podTargetLabels: []
      port: metrics
      targetPort: ""
      interval: ""
      scrapeTimeout: ""
      relabellings: []
      relabelings: []
      metricRelabelings: []
      additionalLabels: {}
      scheme: http
      tlsConfig: {}
    podMonitor:
      enabled: false
      interval: ""
      scrapeTimeout: ""
      namespace: ""
      additionalLabels: {}
      relabelings: []
      metricRelabelings: []
  operator:
    enabled: false
    port: 8080
    serviceMonitor:
      enabled: false
      jobLabel: ""
      targetLabels: []
      podTargetLabels: []
      port: metrics
      targetPort: ""
      interval: ""
      scrapeTimeout: ""
      relabellings: []
      relabelings: []
      metricRelabelings: []
      additionalLabels: {}
      scheme: http
      tlsConfig: {}
    podMonitor:
      enabled: false
      interval: ""
      scrapeTimeout: ""
      namespace: ""
      additionalLabels: {}
      relabelings: []
      metricRelabelings: []
    prometheusRules:
      enabled: false
      namespace: ""
      additionalLabels: {}
      alerts:
        []
  webhooks:
    enabled: false
    port: 8080
    serviceMonitor:
      enabled: false
      jobLabel: ""
      targetLabels: []
      podTargetLabels: []
      port: metrics
      targetPort: ""
      interval: ""
      scrapeTimeout: ""
      relabellings: []
      relabelings: []
      metricRelabelings: []
      additionalLabels: {}
      scheme: http
      tlsConfig: {}
    prometheusRules:
      enabled: false
      namespace: ""
      additionalLabels: {}
      alerts: []
opentelemetry:
  collector:
    uri: ""
  operator:
    enabled: false
certificates:
  autoGenerated: true
  secretName: kedaorg-certs
  mountPath: /certs
  certManager:
    enabled: false
    duration: 8760h0m0s 
    renewBefore: 5840h0m0s 
    generateCA: true
    caSecretName: "kedaorg-ca"
    secretTemplate: {}
    issuer:
      generate: true
      name: foo-org-ca
      kind: ClusterIssuer
      group: cert-manager.io
  operator:
permissions:
  metricServer:
    restrict:
      secret: false
  operator:
    restrict:
      secret: false
      namesAllowList: []
      serviceAccountTokenCreationRoles: []
      allowAllServiceAccountTokenCreation: false
extraObjects: []
asciiArt: true
customManagedBy: ""
enableServiceLinks: true
