global:
  image:
    registry: null
  dnsConfig: {}
image:
  keda:
    registry: ghcr.io
    repository: kedacore/keda
    tag: "2.19.0"
  metricsApiServer:
    registry: ghcr.io
    repository: kedacore/keda-metrics-apiserver
    tag: "2.19.0"
  webhooks:
    registry: ghcr.io
    repository: kedacore/keda-admission-webhooks
    tag: "2.19.0"
  pullPolicy: Always
clusterName: kubernetes-default
clusterDomain: cluster.local
operator:
  name: keda-operator
  revisionHistoryLimit: 10
  replicaCount: 1
  disableCompression: true
  dnsConfig: {}
  dnsPolicy: ClusterFirst
  useHostNetwork: false
  affinity: {}
  extraContainers: []
  extraInitContainers: []
resources:
  operator:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metricServer:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  webhooks:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
prometheus:
  operator:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
  webhooks:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
